dependencies:
- python>=3.6
- category_encoders
- configparser
- cython
- dataclasses
- eli5
- flit
- git
- glob2
- imbalanced-learn
- ipykernel
- ipython
- matplotlib
- mlxtend
- more-itertools
- numpy
- pandas
- pip
- pip: 
  - tensorflow-gpu==2.0.0-rc0
- pyqt
- pystan
- python-docx
- pytorch
- py-xgboost
- scikit-learn
- scikit-optimize
- scipy
- seaborn
- setuptools
- shap
- sphinx
- sqlalchemy
- statsmodels
- sympy
- yellowbrick
- cudatoolkit
- cudnn
- cuml
- cudf