name: mlearn
channels:
- conda-forge
dependencies:
- python
- category_encoders
- configparser
- cudatoolkit
- cudnn
- cython
- dataclasses
- eli5
- git
- imbalanced-learn 
- matplotlib
- more-itertools
- numpy
- pandas
- pip
- py-xgboost
- scikit-learn
- scipy
- seaborn
- shap
- spyder
- statsmodels
- sympy
- xlrd
- yaml